name: deploy s3 static website
run-name:  Beginner Project – “Static Product Portfolio Site”
on:
  push:
permissions: 
  id-token: write
  contents: read
jobs:
  web-content-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Lint HTML files
        run: npx htmlhint "**/*.html"
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-files
          path: '**/*.html'
  test-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: config AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: test Workspace
        run: terraform workspace select test || terraform workspace new test
      - name: Terraform plan
        run: terraform plan -out=tfplan
      - name: artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan
  test-deploy:
    runs-on: ubuntu-latest
    needs: test-infrastructure
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: config AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume:  ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform/
      - name: Terraform init
        run: terraform init
      - name: test Workspace
        run: terraform workspace select test || terraform workspace new test
      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
      - name: Terraform output
        id: output
        run: echo "static_website_url=$(terraform output static_website_url)" >> $GITHUB_ENV
  upload-website:
    runs-on: ubuntu-latest
    needs: [web-content-test, test-deploy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: html-files
      - name: config AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
      - name: install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Upload files to S3
        run: |
          aws s3 sync . s3://$AWS_S3_BUCKET_NAME --exclude "*" --include "*.html" --acl public-read