name: deploy s3 static website
run-name:  Beginner Project – “Static Product Portfolio Site”
on:
  push:
jobs:
  web-content-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: 
        run: npx htmlhint "**/*.html"
  test-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -out=tfplan
      - name: artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan